services:
    db:
        container_name: database
        image: mariadb:jammy
        volumes:
            - ./DB_SQL:/var/lib/mysql
        environment:
            MARIADB_USER: copca
            MARIADB_PASSWORD: 123456
            MARIADB_ROOT_PASSWORD: copca_root
            MARIADB_DATABASE: quiosko_app
        restart: always
        ports:
            - 3306:3306

    # myAdmin:
    #     container_name: phpmyadmin
    #     image: phpmyadmin:5.2.0-apache
    #     ports:
    #         - 8080:80
    #     environment:
    #         PMA_ARBITRARY: 1
    #     depends_on:
    #         - db
    #     restart: always
# volumes:
#     postgres-db:
#         external: true
